@startuml
entity "Question" as question {
  *id: number
  text: string
  ---
  creationDate: Date
  lastModified: Date
}

entity "Option" as option {
  *id: number
  text: string
  value: number
  ---
  question_id:number <<FK>>
  creationDate: Date
  lastModified: Date
}

entity "Response" as response {
  *id: number
  submit_date: date
  ---
  question_id: number <<FK>>
  option_id:number <<FK>>
}
question }|-- option
response }|-- question
@enduml
